name: Build, Package, Release [dev]

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.21"

      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MO_CLI_TOKEN }}

      # - name: Create Sematic Release Version
      #   run: |
      #     git config --global user.email "ruediger@pretzlaff.info"
      #     git config --global user.name "ruedigerp"
      #     git config --global credential.helper cache
      #     npx standard-version --prerelease dev
      #     git push --follow-tags origin delevop

      - name: release-please 
        uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.MO_CLI_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
          target-branch: ${{ github.ref_name }}

      - name: Get the current version
        id: get_version
        run: echo "VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Create release in another repo
        run: |
          echo "Creating release ${VERSION}"
          gh release create refs/tags/${VERSION} --title "Release ${VERSION}" --repo ruedigerp/homebrew-dns-manager
        env:
          GH_TOKEN: ${{ secrets.MO_CLI_TOKEN }}

      - name: Execute make all
        run: make -f Makefile-dev all

      - name: Package artefacts
        run: |
          for file in builds/*; do
            tar -czvf builds/$(basename "$file").tar.gz -C builds $(basename "$file")
          done
          ls -lisa builds

      - name: Upload tarballs/executables
        run: |
          ls -lisa builds
          for tarball in builds/*.tar.gz; do
            gh release upload "${{ env.VERSION }}" "$tarball" --repo ruedigerp/homebrew-dns-manager-dev
          done
          gh release upload "${{ env.VERSION }}" "builds/dns-manager-dev-${{ env.VERSION }}-windows-amd64" --repo ruedigerp/homebrew-dns-manager-dev
        env:
          GH_TOKEN: ${{ secrets.MO_CLI_TOKEN }}

      - name: Update Homebrew & Scoop
        run: |
          ./release-dev.sh
          git config --global user.email "ruediger@pretzlaff.info"
          git config --global user.name "ruedigerp"
          git config --global credential.helper cache
          git clone https://${{secrets.MO_CLI_TOKEN}}@github.com/ruedigerp/homebrew-dns-manager-dev
          cd homebrew-dns-manager-dev
          cp ../dns-manager-dev.rb .
          cp ../dns-manager-dev.json .
          cp ../CHANGELOG.md .
          git add .
          git commit -m " ${{ env.VERSION }}"
          git push
        env:
          GH_TOKEN: ${{ secrets.MO_CLI_TOKEN }}